// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsaoltgTqrzEWK4__cuDxjjAe-CXrzUDQ',
    appId: '1:697469755928:web:4f819f90d91fa2228dd96d',
    messagingSenderId: '697469755928',
    projectId: 'pandavip',
    authDomain: 'pandavip.firebaseapp.com',
    storageBucket: 'pandavip.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3FVEOvQOwEpcTuegRWExVIQ53rOopkLU',
    appId: '1:697469755928:android:3daba24b5e83fd8c8dd96d',
    messagingSenderId: '697469755928',
    projectId: 'pandavip',
    storageBucket: 'pandavip.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANBwZiWMQqRywcXQ-jVkT9TrcByG2_mdg',
    appId: '1:697469755928:ios:f1f8c28bca47373f8dd96d',
    messagingSenderId: '697469755928',
    projectId: 'pandavip',
    storageBucket: 'pandavip.firebasestorage.app',
    iosBundleId: 'com.tiopanda.pandavip',
  );
}
